

GET http://localhost:4000/accesorios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc3VhcmlvcyI6eyJfaWQiOiI2MmUyODJhYjQyZjRhMDdiY2ZhMTI0MzEiLCJlbWFpbCI6ImFsZXhpczJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkS1lmd0p4MlZBRnkyeEpqYzZQbC5hZVpvNEVVWVZmTWJqRHFUbzVMUUV6bUsvM0tSNjFja1ciLCJub21icmUiOiJhbGV4aXMiLCJhcGVsbGlkbyI6InBpbmEiLCJjYXJyaXRvRGVDb21wcmEiOltdLCJoaXN0b3JpYWxEZUNvbXByYSI6W10sImZhdm9yaXRvcyI6W10sImFkbWluIjpmYWxzZSwiX192IjowfSwiaWF0IjoxNjU5MTIyNjA4LCJleHAiOjE2NTkxNTg2MDh9.oBjW4ffRueTWFSLO7lOrMMIeLBnhZT3KLcTrk4hP4DQ